Update 1-run_nginx_as_nginx

diff --git a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
--- a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
+++ b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
@@ -1,17 +1,23 @@
 #!/usr/bin/env bash
-# This script configures Nginx to run as nginx user and listen on all active IPs on port 8080
+# Run Nginx as the nginx privileged user on port 8080
 
-# Backup the original Nginx configuration file
-cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
+# Check if the nginx user exists
+if ! id -u nginx &>/dev/null; then
+    echo "Error: nginx user does not exist."
+    exit 1
+fi
 
-# Update the Nginx configuration to run as the nginx user and listen on port 8080
-sed -i 's/user  nginx;/user  nginx;\n    listen 8080;/g' /etc/nginx/nginx.conf
+# Update Nginx configuration to run as nginx user
+sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
 
-# Restart Nginx to apply the changes
-service nginx restart
+# Update default site configuration to listen on port 8080
+sed -i "s/80/8080/g" /etc/nginx/sites-available/default
 
-# Display Nginx processes
-ps auxff | grep ngin[x]
+# Change permissions on nginx.conf
+chmod 644 /etc/nginx/nginx.conf
 
-# Check if Nginx is listening on port 8080
-nc -z 0 8080
+# Kill Apache2 service if it's running
+pkill apache2
+
+# Restart Nginx using the service command
+sudo service nginx restart
